[project]
name = "siomay"
version = "2026.1.9"
description = "SIOMAY: Sistem Otomasi Massal dan Terpercaya"
readme = "README.md"
requires-python = ">=3.13,<3.15"
dependencies = [
    "flet>=0.86.0",
    "pandas>=2.0.0",
    "openpyxl>=3.1.0",
    "python-docx>=1.1.0",
    "pypdf>=4.0.0",
    "PyMuPDF>=1.24.0",
    "Pillow>=10.0.0",
    "pillow-heif>=1.1.0",
    "requests>=2.28.0",
    "certifi>=2024.0.0",
]

[tool.flet]
org = "id.go.bps"
product = "SIOMAY"
company = "6304 - Muhammad Julian Firdaus, S.Tr.Stat."
copyright = "Copyright (c) 2026 6304 - Muhammad Julian Firdaus, S.Tr.Stat."

[tool.flet.app]
path = "."
module = "app"

[tool.flet.assets]
dir = "assets"

[tool.siomay.release]
display-version = "v2026.1.9"
package-version = "2026.1.9"
channel = "stable"
windows-minimum-version = "Windows 10 version 1809 (x64)"
windows-architecture = "x64"
application-identifier = "id.go.bps.siomay"
repository = "https://github.com/archainur/siomay-se26"
